steps:
  # Build the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-backend:$SHORT_SHA",
        ".",
      ]
    dir: "backend"
  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-backend:$SHORT_SHA"]
  # Tag the image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "artifacts"
      - "docker"
      - "tags"
      - "add"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-backend:$SHORT_SHA"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-backend:latest"
  # Tag the image with the version
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "artifacts"
      - "docker"
      - "tags"
      - "add"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-backend:$SHORT_SHA"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-backend:v1"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
        - "run"
        - "deploy"
        - "swim-rag-backend"
        - "--image"
        - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-backend:$SHORT_SHA"
        - "--region"
        - "${_REGION}"
        - "--platform=managed"
        - "--no-allow-unauthenticated"
        - "--service-account=${_SERVICE_ACCOUNT}"
        - "--set-env-vars=PROJECT_ID=${_PROJECT_ID}"
        - "--set-env-vars=REGION=${_REGION}"
        - "--set-env-vars=MODEL=${_MODEL}"
        - "--set-env-vars=EMBEDDING_NAME=${_EMBEDDING_NAME}"
        - "--set-env-vars=EMBEDDING_MODEL=${_EMBEDDING_MODEL}"
        - "--set-env-vars=EMBEDDING_SIZE=${_EMBEDDING_SIZE}"
        - "--set-env-vars=DB_NAME=${_DB_NAME}"
        - "--set-env-vars=DB_INSTANCE=${_DB_INSTANCE}"
        - "--set-env-vars=DB_USER=${_DB_USER}"
        - "--set-env-vars=DB_PASS_LOCATION=${_DB_PASS_LOCATION}"
        - "--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}"
        - "--set-env-vars=BUCKET_NAME=${_BUCKET_NAME}"
images: ["$LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-backend:$SHORT_SHA"]
options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: "go-cache"
      path: "/go"
  env:
    - "GOCACHE=/go"
