steps:
  - name: "node:20"
    entrypoint: "npm"
    args: ["install"]
    id: "Install"

  - name: "node:20"
    entrypoint: "npm"
    args: ["test"]
    id: "Test"

options:
  logging: CLOUD_LOGGING_ONLY
