steps:
  # Install dependencies
  - name: "node:22"
    entrypoint: "npm"
    args: ["install"]
    dir: "frontend"
  # Run lint
  - name: "node:22"
    entrypoint: "npm"
    args: ["run", "lint"]
    dir: "frontend"
  # Run type-check
  - name: "node:22"
    entrypoint: "npm"
    args: ["run", "type-check"]
    dir: "frontend"
  # Run tests
  - name: "node:22"
    entrypoint: "npm"
    args: ["run", "test"]
    dir: "bff"
  # Run lint
  - name: "node:22"
    entrypoint: "npm"
    args: ["run", "lint"]
    dir: "bff"
  # Run type-check
  - name: "node:22"
    entrypoint: "npm"
    args: ["run", "type-check"]
    dir: "bff"
  # Run tests
  - name: "node:22"
    entrypoint: "npm"
    args: ["run", "test"]
    dir: "bff"
options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
  env:
    - "BACKEND_URL=${_BACKEND_URL}"
    - "FRONTEND_URL=${_FRONTEND_URL}"
