steps:
  # Build the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-mcp:$SHORT_SHA",
        ".",
      ]
    dir: "."
  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-mcp:$SHORT_SHA"]
  # Tag the image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "artifacts"
      - "docker"
      - "tags"
      - "add"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-mcp:$SHORT_SHA"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-mcp:latest"
  # Tag the image with the version
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "artifacts"
      - "docker"
      - "tags"
      - "add"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-mcp:$SHORT_SHA"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-mcp:v1"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
        - "run"
        - "deploy"
        - "swim-rag-mcp"
        - "--image"
        - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/swim-rag-mcp:$SHORT_SHA"
        - "--region"
        - "${_REGION}"
        - "--platform=managed"
        - "--no-allow-unauthenticated"
        - "--service-account=${_SERVICE_ACCOUNT}"
        - "--cpu=${_SERVICE_CPU}"
        - "--memory=${_SERVICE_MEMORY}"
        - "--timeout=${_SERVICE_TIMEOUT}"
        - "--set-env-vars=PROJECT_ID=${_PROJECT_ID}"
        - "--set-env-vars=REGION=${_REGION}"
        - "--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}"
options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: "uv-cache"
      path: "/root/.cache/uv"
  env:
    - "UV_CACHE_DIR=/root/.cache/uv"
