// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload and store a new user created swim training plan in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "Upload a new private training plan",
                "parameters": [
                    {
                        "description": "Training plan data",
                        "name": "plan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UploadPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Plan added successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/add-plan-to-history": {
            "post": {
                "description": "Add a plan to the authenticated user's history with a new id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training Plans"
                ],
                "summary": "Add a plan to user history",
                "parameters": [
                    {
                        "description": "Plan to add to history",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddPlanToHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AddPlanToHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/chat": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Have a conversation with the AI trainer to create, modify, or get information about training plans",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Chat with AI to create or refine training plans",
                "parameters": [
                    {
                        "description": "Chat request with message and optional plan ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful chat response with updated plan",
                        "schema": {
                            "$ref": "#/definitions/models.ChatResponsePayload"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drill": {
            "get": {
                "description": "Get a drill exercise by its image name identifier and language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drills"
                ],
                "summary": "Get a single drill",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drill image name (unique identifier)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Language code (en, de)",
                        "name": "lang",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Drill"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Drill not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drills/options": {
            "get": {
                "description": "Fetch unique values for drill filters (styles, target groups, etc.) based on language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drills"
                ],
                "summary": "Get drill filter options",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language code (en, de)",
                        "name": "lang",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rag.DrillFilterOptions"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drills/search": {
            "get": {
                "description": "Search drill exercises with optional filters for language, target groups, styles, and difficulty",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drills"
                ],
                "summary": "Search drills",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language code (en, de)",
                        "name": "lang",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Target groups filter (e.g., Beginner, Competitive Swimmer)",
                        "name": "target_groups",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Styles filter (e.g., Freestyle, Backstroke)",
                        "name": "styles",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Difficulty filter (Easy, Medium, Hard)",
                        "name": "difficulty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rag.DrillSearchResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/export-pdf": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate and download a PDF version of a training plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training Plans"
                ],
                "summary": "Export training plan to PDF",
                "parameters": [
                    {
                        "description": "Training plan data to export",
                        "name": "plan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PlanToPDFRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PDF export response with URI",
                        "schema": {
                            "$ref": "#/definitions/models.PlanToPDFResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/feedback": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit a rating, was_swam status, and difficulty rating for a training plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "Submit feedback for a training plan",
                "parameters": [
                    {
                        "description": "Feedback data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Feedback submitted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/file-to-plan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Convert a file containing a training plan to a structured plan. Supports PNG, JPEG, and PDF formats.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "Convert a file (image or PDF) of a plan to a plan",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File containing a plan (PNG, JPEG, or PDF)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Plan ID of the converted plan",
                        "schema": {
                            "$ref": "#/definitions/models.RAGResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request or unsupported file type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/generate-prompt": {
            "post": {
                "description": "Generate a prompt for the LLM based on the provided language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training Plans"
                ],
                "summary": "Generate a prompt for the LLM",
                "parameters": [
                    {
                        "description": "Request to generate a prompt",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GeneratePromptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Generated prompt response",
                        "schema": {
                            "$ref": "#/definitions/models.GeneratedPromptResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API including database and vector store connectivity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Comprehensive health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthStatus"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/models.HealthStatus"
                        }
                    }
                }
            }
        },
        "/health-basic": {
            "get": {
                "description": "Returns a simple OK response for basic health monitoring",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Basic health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/memory/conversation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the full conversation history for a specific plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Memory"
                ],
                "summary": "Get conversation history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plan ID",
                        "name": "plan_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversation history",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MessagePayload"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete all messages in a conversation for a specific plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Memory"
                ],
                "summary": "Delete an entire conversation",
                "parameters": [
                    {
                        "description": "Request to delete a conversation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversation deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/memory/message": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a new message to the conversation history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Memory"
                ],
                "summary": "Add a message to conversation",
                "parameters": [
                    {
                        "description": "Request to add a message",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message added successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a specific message from the conversation history while maintaining the linked list integrity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Memory"
                ],
                "summary": "Delete a single message from conversation",
                "parameters": [
                    {
                        "description": "Request to delete a message",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/memory/messages-after": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a message and all messages that follow it in the conversation, allowing conversation branching",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Memory"
                ],
                "summary": "Delete a message and all subsequent messages",
                "parameters": [
                    {
                        "description": "Request to delete messages from a point",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteMessagesAfterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Messages deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/plan/{plan_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a training plan from the authenticated user's history and remove all associated data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training Plans"
                ],
                "summary": "Delete a training plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plan ID to delete",
                        "name": "plan_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Plan deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Plan not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/query": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Query the RAG system for relevant training plans based on input",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training Plans"
                ],
                "summary": "Query training plans",
                "parameters": [
                    {
                        "description": "Query parameters",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query results",
                        "schema": {
                            "$ref": "#/definitions/models.RAGResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/share-plan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Share a training plan via link or email. Email sharing is not implemented yet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training Plans"
                ],
                "summary": "Share a training plan",
                "parameters": [
                    {
                        "description": "Request to share a training plan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SharePlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Share plan response with URI",
                        "schema": {
                            "$ref": "#/definitions/models.SharePlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/uploads": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all plans uploaded by the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "Get uploaded plans",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DonatedPlan"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/uploads/{plan_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a specific plan uploaded by the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "Get a uploaded plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plan ID",
                        "name": "plan_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DonatedPlan"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Plan not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upsert-plan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing training plan if it belongs to the user, or insert a new one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training Plans"
                ],
                "summary": "Update or insert a training plan into a user's history",
                "parameters": [
                    {
                        "description": "Request to upsert a training plan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpsertPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Plan ID of the upserted training plan",
                        "schema": {
                            "$ref": "#/definitions/models.UpsertPlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently delete the authenticated user's account and all associated data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete user account",
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddMessageRequest": {
            "description": "Request payload for adding a message to the conversation history",
            "type": "object",
            "required": [
                "content",
                "plan_id",
                "role"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "plan_snapshot": {
                    "$ref": "#/definitions/models.RAGResponse"
                },
                "previous_message_id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                }
            }
        },
        "models.AddPlanToHistoryRequest": {
            "description": "Request payload for adding a plan to the authenticated user's history",
            "type": "object",
            "required": [
                "description",
                "plan_id",
                "table",
                "title"
            ],
            "properties": {
                "description": {
                    "description": "Description of the plan",
                    "type": "string",
                    "example": "A comprehensive training plan for improving freestyle technique"
                },
                "plan_id": {
                    "description": "PlanID identifies the plan to add to history",
                    "type": "string",
                    "example": "plan_123"
                },
                "table": {
                    "description": "A structured training plan table containing exercise rows",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Row"
                    }
                },
                "title": {
                    "description": "Title of the plan",
                    "type": "string",
                    "example": "Advanced Freestyle Training"
                }
            }
        },
        "models.AddPlanToHistoryResponse": {
            "description": "Response containing the new plan ID and a success message",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Plan added to history successfully"
                },
                "plan_id": {
                    "type": "string",
                    "example": "plan_123"
                }
            }
        },
        "models.ChatRequest": {
            "description": "Request payload for conversational training plan creation and refinement",
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "language": {
                    "description": "Language specifies the language for the response",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Language"
                        }
                    ],
                    "example": "en"
                },
                "message": {
                    "description": "Message is the user's input to the chat",
                    "type": "string",
                    "example": "Make it more challenging"
                },
                "plan_id": {
                    "description": "PlanID identifies the conversation/plan (optional for new conversations)",
                    "type": "string",
                    "example": "plan_123"
                },
                "pool_length": {
                    "description": "PoolLength specifies the pool length for the training plan"
                }
            }
        },
        "models.ChatResponsePayload": {
            "description": "Response containing the updated plan and conversational response",
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description of the training plan",
                    "type": "string",
                    "example": "A comprehensive training plan for improving freestyle technique"
                },
                "plan_id": {
                    "description": "PlanID identifies the conversation/plan",
                    "type": "string",
                    "example": "plan_123"
                },
                "response": {
                    "description": "Response is the conversational AI response explaining changes",
                    "type": "string",
                    "example": "I've made the plan more challenging by adding butterfly sets"
                },
                "table": {
                    "description": "A structured training plan table containing exercise rows",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Row"
                    }
                },
                "title": {
                    "description": "Title of the training plan",
                    "type": "string",
                    "example": "Advanced Freestyle Training"
                }
            }
        },
        "models.DeleteConversationRequest": {
            "description": "Request payload for deleting an entire conversation and all its messages",
            "type": "object",
            "required": [
                "plan_id"
            ],
            "properties": {
                "plan_id": {
                    "description": "PlanID identifies the conversation to delete",
                    "type": "string",
                    "example": "plan_123"
                }
            }
        },
        "models.DeleteMessageRequest": {
            "description": "Request payload for deleting a single message from conversation history",
            "type": "object",
            "required": [
                "message_id"
            ],
            "properties": {
                "message_id": {
                    "description": "MessageID identifies the message to delete",
                    "type": "string",
                    "example": "msg_123"
                }
            }
        },
        "models.DeleteMessagesAfterRequest": {
            "description": "Request payload for deleting a message and all subsequent messages in the conversation",
            "type": "object",
            "required": [
                "message_id"
            ],
            "properties": {
                "message_id": {
                    "description": "MessageID identifies the message from which to delete (inclusive)",
                    "type": "string",
                    "example": "msg_123"
                }
            }
        },
        "models.DonatedPlan": {
            "type": "object",
            "properties": {
                "allow_sharing": {
                    "description": "AllowSharing indicates if the plan can be used in the RAG system",
                    "type": "boolean"
                },
                "created_at": {
                    "description": "CreatedAt is the time the plan was donated as a datetime string",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "table": {
                    "description": "Table is the table associated with the plan",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Row"
                    }
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.Drill": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "difficulty": {
                    "type": "string"
                },
                "img_description": {
                    "type": "string"
                },
                "img_name": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "short_description": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "styles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "video_url": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.FeedbackRequest": {
            "description": "Request payload for submitting feedback on a training plan",
            "type": "object",
            "required": [
                "plan_id",
                "rating"
            ],
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "Great plan!"
                },
                "difficulty_rating": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 1,
                    "example": 7
                },
                "plan_id": {
                    "type": "string",
                    "example": "plan_123"
                },
                "rating": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 5
                },
                "was_swam": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.GeneratePromptRequest": {
            "description": "Request payload for generating a prompt for swim training plan creation",
            "type": "object",
            "required": [
                "language"
            ],
            "properties": {
                "language": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Language"
                        }
                    ],
                    "example": "en"
                }
            }
        },
        "models.GeneratedPromptResponse": {
            "description": "Response containing the generated prompt for swim training plan creation",
            "type": "object",
            "properties": {
                "prompt": {
                    "type": "string",
                    "example": "Generate a swim training plan for improving freestyle technique"
                }
            }
        },
        "models.HealthStatus": {
            "description": "Health status of the service and its components",
            "type": "object",
            "properties": {
                "components": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "schema_version": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.Language": {
            "type": "string",
            "enum": [
                "en",
                "de"
            ],
            "x-enum-varnames": [
                "LanguageEN",
                "LanguageDE"
            ]
        },
        "models.MessagePayload": {
            "description": "Snapshot of a training plan",
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "description": "Table containing the training plan details",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "next_message_id": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "plan_snapshot": {
                    "$ref": "#/definitions/models.RAGResponse"
                },
                "previous_message_id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.PlanToPDFRequest": {
            "description": "Request payload for exporting a training plan to PDF format",
            "type": "object",
            "required": [
                "description",
                "table",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "A comprehensive training plan for improving freestyle technique"
                },
                "frontend_base_url": {
                    "description": "FrontendBaseURL is the base URL for drill links in the PDF",
                    "type": "string",
                    "example": "https://swim-gen.app"
                },
                "horizontal": {
                    "description": "Horizontal indicates if the PDF should be in landscape orientation",
                    "type": "boolean",
                    "example": false
                },
                "language": {
                    "description": "Language specifies the language for the PDF content",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Language"
                        }
                    ],
                    "example": "en"
                },
                "large_font": {
                    "description": "LargeFont indicates if the PDF should use a larger font size",
                    "type": "boolean",
                    "example": true
                },
                "plan_id": {
                    "description": "PlanID identifies the training plan to be exported",
                    "type": "string",
                    "example": "plan_123"
                },
                "table": {
                    "description": "A structured training plan table containing exercise rows",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Row"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Advanced Freestyle Training"
                }
            }
        },
        "models.PlanToPDFResponse": {
            "description": "Response containing the URI to the generated PDF file",
            "type": "object",
            "properties": {
                "uri": {
                    "type": "string",
                    "example": "https://storage.googleapis.com/bucket/plans/plan_123.pdf"
                }
            }
        },
        "models.QueryRequest": {
            "description": "Request payload for querying swim training plans from the RAG system",
            "type": "object",
            "required": [
                "content",
                "method"
            ],
            "properties": {
                "content": {
                    "description": "Content describes what kind of training plan is needed",
                    "type": "string",
                    "example": "I need a training plan for improving my freestyle technique"
                },
                "filter": {
                    "description": "Filter allows filtering plans by metadata like difficulty or stroke type",
                    "type": "object",
                    "additionalProperties": {}
                },
                "language": {
                    "description": "Language specifies the language for the response",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Language"
                        }
                    ],
                    "example": "en"
                },
                "method": {
                    "description": "Method can be either 'choose' (select existing plan) or 'generate' (create new plan)",
                    "type": "string",
                    "enum": [
                        "choose",
                        "generate"
                    ],
                    "example": "generate"
                },
                "pool_length": {
                    "description": "PoolLength specifies the pool length for the training plan"
                },
                "preferences": {
                    "description": "Preferences indicates if the user profile should be used for generation",
                    "type": "boolean"
                }
            }
        },
        "models.RAGResponse": {
            "description": "Response containing a generated or selected swim training plan",
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "A comprehensive training plan for improving freestyle technique"
                },
                "plan_id": {
                    "description": "PlanID is the identifier of the training plan",
                    "type": "string",
                    "example": "plan_123"
                },
                "table": {
                    "description": "A structured training plan table containing exercise rows",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Row"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Advanced Freestyle Training"
                }
            }
        },
        "models.Role": {
            "type": "string",
            "enum": [
                "user",
                "ai"
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleAI"
            ]
        },
        "models.Row": {
            "description": "A single exercise entry with amount, distance, breaks, content, intensity and total volume",
            "type": "object",
            "properties": {
                "Amount": {
                    "type": "integer",
                    "example": 4
                },
                "Break": {
                    "type": "string",
                    "example": "20"
                },
                "Content": {
                    "type": "string",
                    "example": "Freestyle swim"
                },
                "Distance": {
                    "type": "integer",
                    "example": 100
                },
                "Intensity": {
                    "type": "string",
                    "example": "Easy"
                },
                "Multiplier": {
                    "type": "string",
                    "example": "x"
                },
                "Sum": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "models.SharePlanRequest": {
            "description": "Request payload for sharing a swim training plan",
            "type": "object",
            "required": [
                "method",
                "plan_id"
            ],
            "properties": {
                "method": {
                    "description": "Method specifies the sharing method, e.g., 'link' or 'email'",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SharingMethod"
                        }
                    ],
                    "example": "link"
                },
                "plan_id": {
                    "description": "PlanID identifies the training plan to be shared",
                    "type": "string",
                    "example": "plan_123"
                }
            }
        },
        "models.SharePlanResponse": {
            "description": "Response containing the sharing details of the swim training plan",
            "type": "object",
            "properties": {
                "url_hash": {
                    "description": "URLHash is the hash to access the shared training plan",
                    "type": "string",
                    "example": "abc123"
                }
            }
        },
        "models.SharingMethod": {
            "type": "string",
            "enum": [
                "link",
                "email"
            ],
            "x-enum-varnames": [
                "SharingMethodLink",
                "SharingMethodEmail"
            ]
        },
        "models.UploadPlanRequest": {
            "description": "Request payload for donating a swim training plan to the system",
            "type": "object",
            "required": [
                "table"
            ],
            "properties": {
                "allow_sharing": {
                    "description": "AllowSharing indicates if the plan can be shared with others",
                    "type": "boolean"
                },
                "description": {
                    "type": "string",
                    "example": "A comprehensive training plan for improving freestyle technique"
                },
                "language": {
                    "description": "Language specifies the language of the training plan",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Language"
                        }
                    ],
                    "example": "en"
                },
                "table": {
                    "description": "A structured training plan table containing exercise rows",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Row"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Advanced Freestyle Training"
                }
            }
        },
        "models.UpsertPlanRequest": {
            "description": "Request payload for upserting a swim training plan to the system",
            "type": "object",
            "required": [
                "description",
                "table",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "A comprehensive training plan for improving freestyle technique"
                },
                "plan_id": {
                    "description": "PlanID identifies the training plan to be upserted",
                    "type": "string",
                    "example": "plan_123"
                },
                "table": {
                    "description": "A structured training plan table containing exercise rows",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Row"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Advanced Freestyle Training"
                }
            }
        },
        "models.UpsertPlanResponse": {
            "description": "Response containing the upserted swim training plan",
            "type": "object",
            "properties": {
                "plan_id": {
                    "type": "string",
                    "example": "plan_123"
                }
            }
        },
        "rag.DrillFilterOptions": {
            "type": "object",
            "properties": {
                "difficulties": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "styles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "rag.DrillSearchResult": {
            "type": "object",
            "properties": {
                "drills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Drill"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the JWT.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swim Gen API",
	Description:      "A REST API for swim training plan management with RAG capabilities",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
