-- Seed data for local development

-- Generate UUIDs for reuse throughout the seed data
DO $$
DECLARE
  v_collection_id uuid := gen_random_uuid();
  v_plan1_id uuid := gen_random_uuid();
  v_plan2_id uuid := gen_random_uuid();
  v_plan3_id uuid := gen_random_uuid();
  v_user1_id uuid := gen_random_uuid();
  v_user2_id uuid := gen_random_uuid();
  v_embedding1_id uuid := gen_random_uuid();
  v_embedding2_id uuid := gen_random_uuid();
  v_embedding3_id uuid := gen_random_uuid();
BEGIN
  -- Insert embedders (collection)
  INSERT INTO embedders (name, cmetadata, uuid) VALUES
    ('gemini-embedding-001', '{"model": "gemini-embedding-001", "dimensions": 768}', v_collection_id)
  ON CONFLICT (name) DO NOTHING;

  -- Insert test plans
  INSERT INTO plans (plan_id, title, description, plan_table, created_at) VALUES
    (
      v_plan1_id,
      'Grundlagenausdauer - 2000m',
      'Ein klassisches Grundlagenausdauer-Training für Fortgeschrittene mit Fokus auf Kraul und gleichmäßige Intensität.',
      '[
        {"Amount": 1, "Multiplier": "x", "Distance": 200, "Break": "0", "Content": "Einschwimmen locker", "Intensity": "leicht", "Sum": 200},
        {"Amount": 4, "Multiplier": "x", "Distance": 100, "Break": "20", "Content": "Kraul mit Atmung 3er", "Intensity": "mittel", "Sum": 400},
        {"Amount": 1, "Multiplier": "x", "Distance": 400, "Break": "60", "Content": "Kraul gleichmäßig", "Intensity": "mittel", "Sum": 400},
        {"Amount": 8, "Multiplier": "x", "Distance": 50, "Break": "10", "Content": "Kraul Technik", "Intensity": "leicht", "Sum": 400},
        {"Amount": 1, "Multiplier": "x", "Distance": 200, "Break": "0", "Content": "Ausschwimmen locker", "Intensity": "leicht", "Sum": 200},
        {"Amount": 0, "Multiplier": "", "Distance": 0, "Break": "", "Content": "Gesamt", "Intensity": "", "Sum": 1600}
      ]'::jsonb,
      NOW() - INTERVAL '10 days'
    ),
    (
      v_plan2_id,
      'Techniktraining - Sprint',
      'Techniktraining mit Sprinteinheiten für Fortgeschrittene. Fokus auf explosive Starts und schnelle Wendungen.',
      '[
        {"Amount": 1, "Multiplier": "x", "Distance": 300, "Break": "0", "Content": "Einschwimmen gemischt", "Intensity": "leicht", "Sum": 300},
        {"Amount": 6, "Multiplier": "x", "Distance": 50, "Break": "30", "Content": "Sprint Kraul mit Startsprung", "Intensity": "hoch", "Sum": 300},
        {"Amount": 4, "Multiplier": "x", "Distance": 25, "Break": "45", "Content": "Maximalsprint", "Intensity": "maximal", "Sum": 100},
        {"Amount": 8, "Multiplier": "x", "Distance": 50, "Break": "20", "Content": "Technikübungen Kraul", "Intensity": "leicht", "Sum": 400},
        {"Amount": 1, "Multiplier": "x", "Distance": 200, "Break": "0", "Content": "Ausschwimmen", "Intensity": "leicht", "Sum": 200},
        {"Amount": 0, "Multiplier": "", "Distance": 0, "Break": "", "Content": "Gesamt", "Intensity": "", "Sum": 1300}
      ]'::jsonb,
      NOW() - INTERVAL '5 days'
    ),
    (
      v_plan3_id,
      'Lagen-Mix Training',
      'Abwechslungsreiches Lagentraining für fortgeschrittene Schwimmer mit allen vier Schwimmarten.',
      '[
        {"Amount": 1, "Multiplier": "x", "Distance": 400, "Break": "0", "Content": "Einschwimmen 100m pro Lage", "Intensity": "leicht", "Sum": 400},
        {"Amount": 4, "Multiplier": "x", "Distance": 100, "Break": "30", "Content": "Lagen (Rücken-Brust-Delfin-Kraul)", "Intensity": "mittel", "Sum": 400},
        {"Amount": 2, "Multiplier": "x", "Distance": 200, "Break": "45", "Content": "Lagen", "Intensity": "mittel-hoch", "Sum": 400},
        {"Amount": 8, "Multiplier": "x", "Distance": 50, "Break": "15", "Content": "Abwechselnd alle Lagen", "Intensity": "mittel", "Sum": 400},
        {"Amount": 1, "Multiplier": "x", "Distance": 200, "Break": "0", "Content": "Ausschwimmen Kraul locker", "Intensity": "leicht", "Sum": 200},
        {"Amount": 0, "Multiplier": "", "Distance": 0, "Break": "", "Content": "Gesamt", "Intensity": "", "Sum": 1800}
      ]'::jsonb,
      NOW() - INTERVAL '2 days'
    )
  ON CONFLICT (plan_id) DO NOTHING;

  -- Insert scraped plans (linking URLs to plans)
  INSERT INTO scraped (url, collection_id, plan_id, created_at) VALUES
    ('https://docswim.de/trainingsplaene/grundlagenausdauer-2000m', v_collection_id, v_plan1_id, NOW() - INTERVAL '10 days'),
    ('https://docswim.de/trainingsplaene/technik-sprint', v_collection_id, v_plan2_id, NOW() - INTERVAL '5 days'),
    ('https://docswim.de/trainingsplaene/lagen-mix', v_collection_id, v_plan3_id, NOW() - INTERVAL '2 days')
  ON CONFLICT (url, collection_id) DO NOTHING;

  -- Insert embeddings for the plans
  -- Note: These are dummy embeddings. In production, these would be generated by the embedding model.
  -- For local testing, you can either:
  -- 1. Generate real embeddings using the backend scraper
  -- 2. Use these dummy embeddings for basic functionality testing
  INSERT INTO embeddings (collection_id, embedding, document, cmetadata, uuid) VALUES
    (
      v_collection_id,
      (SELECT ARRAY(SELECT random() FROM generate_series(1, 768))::vector),
      'Grundlagenausdauer - 2000m:
 Ein klassisches Grundlagenausdauer-Training für Fortgeschrittene mit Fokus auf Kraul und gleichmäßige Intensität.
 | Anzahl |  | Strecke(m) | Pause(s) | Inhalt | Intensität | Umfang |
|---|---|---|---|---|---|---|
| 1 | x | 200 | 0 | Einschwimmen locker | leicht | 200 |
| 4 | x | 100 | 20 | Kraul mit Atmung 3er | mittel | 400 |
| 1 | x | 400 | 60 | Kraul gleichmäßig | mittel | 400 |
| 8 | x | 50 | 10 | Kraul Technik | leicht | 400 |
| 1 | x | 200 | 0 | Ausschwimmen locker | leicht | 200 |
| 0 |  | 0 |  | Gesamt |  | 1600 |
',
      json_build_object('plan_id', v_plan1_id, 'url', 'https://docswim.de/trainingsplaene/grundlagenausdauer-2000m', 'title', 'Grundlagenausdauer - 2000m'),
      v_embedding1_id
    ),
    (
      v_collection_id,
      (SELECT ARRAY(SELECT random() FROM generate_series(1, 768))::vector),
      'Techniktraining - Sprint:
 Techniktraining mit Sprinteinheiten für Fortgeschrittene. Fokus auf explosive Starts und schnelle Wendungen.
 | Anzahl |  | Strecke(m) | Pause(s) | Inhalt | Intensität | Umfang |
|---|---|---|---|---|---|---|
| 1 | x | 300 | 0 | Einschwimmen gemischt | leicht | 300 |
| 6 | x | 50 | 30 | Sprint Kraul mit Startsprung | hoch | 300 |
| 4 | x | 25 | 45 | Maximalsprint | maximal | 100 |
| 8 | x | 50 | 20 | Technikübungen Kraul | leicht | 400 |
| 1 | x | 200 | 0 | Ausschwimmen | leicht | 200 |
| 0 |  | 0 |  | Gesamt |  | 1300 |
',
      json_build_object('plan_id', v_plan2_id, 'url', 'https://docswim.de/trainingsplaene/technik-sprint', 'title', 'Techniktraining - Sprint'),
      v_embedding2_id
    ),
    (
      v_collection_id,
      (SELECT ARRAY(SELECT random() FROM generate_series(1, 768))::vector),
      'Lagen-Mix Training:
 Abwechslungsreiches Lagentraining für fortgeschrittene Schwimmer mit allen vier Schwimmarten.
 | Anzahl |  | Strecke(m) | Pause(s) | Inhalt | Intensität | Umfang |
|---|---|---|---|---|---|---|
| 1 | x | 400 | 0 | Einschwimmen 100m pro Lage | leicht | 400 |
| 4 | x | 100 | 30 | Lagen (Rücken-Brust-Delfin-Kraul) | mittel | 400 |
| 2 | x | 200 | 45 | Lagen | mittel-hoch | 400 |
| 8 | x | 50 | 15 | Abwechselnd alle Lagen | mittel | 400 |
| 1 | x | 200 | 0 | Ausschwimmen Kraul locker | leicht | 200 |
| 0 |  | 0 |  | Gesamt |  | 1800 |
',
      json_build_object('plan_id', v_plan3_id, 'url', 'https://docswim.de/trainingsplaene/lagen-mix', 'title', 'Lagen-Mix Training'),
      v_embedding3_id
    )
  ON CONFLICT (uuid) DO NOTHING;

  -- Insert test donations
  INSERT INTO donations (user_id, plan_id, created_at) VALUES
    (v_user1_id, v_plan1_id, NOW() - INTERVAL '8 days'),
    (v_user1_id, v_plan3_id, NOW() - INTERVAL '1 day')
  ON CONFLICT (user_id, plan_id) DO NOTHING;

  -- Insert test feedback
  INSERT INTO feedback (user_id, plan_id, rating, comment, created_at, updated_at) VALUES
    (v_user1_id, v_plan1_id, 5, 'Sehr guter Plan für Grundlagenausdauer! Hat mir sehr geholfen.', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
    (v_user2_id, v_plan2_id, 4, 'Gute Technikübungen, aber sehr anstrengend für Anfänger.', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
    (v_user1_id, v_plan3_id, 5, 'Perfektes Lagentraining! Sehr abwechslungsreich.', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day')
  ON CONFLICT (user_id, plan_id) DO NOTHING;
END $$;
