
name: 📦 Build Backend

on:
  workflow_call:
      inputs:
        env:
          required: false
          type: string
          description: "Environment to setup for"
          default: dev
        version:
          required: true
          type: string
          description: "The semantic version to be released"
  push:
    branches: [dev]
    paths:
      - "backend/**"
      - ".github/workflows/backend-build.yaml"
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # TODO: use inputs.env if provided, otherwise use github branch-name to autoselect prod/dev
    name: ${{ inputs.env || github.branch.name }} backend environment
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || github.branch.name }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Workflow
        uses: ./.github/actions/setup
        with:
          wif_provider: ${{ vars.wif_provider }}
          wif_sa: ${{ vars.wif_sa }}
          env-file: backend/.env.development

      - name: Build Docker Image
        shell: bash
        run: docker build --platform ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-rag-backend:${{ github.ref }} .
        working-directory: backend
      - name: Push Docker Image to Registry
        shell: bash
        run: docker push ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-rag-backend:${{ github.ref }}

      - name: Tag Image as latest
        shell: bash
        run: |
          gcloud artifacts docker tags add
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-rag-backend:latest

      - name: Tag with main version
        if: startsWith(github.ref, 'refs/tags/main-')
        shell: bash
        run: |
          gcloud artifacts docker tags add
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-rag-backend:${{ inputs.version }}

