name: 🪄 Manual Plan & Apply

on:
  workflow_dispatch:
    inputs:
      env:
        description: Target environment (prod or dev)
        required: true
        type: choice
        options:
          - prod
          - dev
        default: prod
      apply:
        description: Set true to run apply after plan
        required: true
        type: boolean
        default: false
      version:
        description: Version tag to deploy (only for prod)
        required: false
        type: string
        default: latest

permissions:
  id-token: write
  contents: write

concurrency:
  group: manual-tofu-${{ inputs.env }}
  cancel-in-progress: false

jobs:
  opentofu-infra:
    name: 🪄 OpenTofu infra (${{ inputs.env }})
    uses: ./.github/workflows/tf-plan-apply.yaml
    with:
      env: ${{ inputs.env }}
      apply: ${{ inputs.apply }}
      cwd: deployments/${{ inputs.env }}/0-infra
    secrets: inherit

  opentofu-services:
    name: 🪄 OpenTofu services (${{ inputs.env }})
    needs:
      - opentofu-infra
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    uses: ./.github/workflows/tf-plan-apply.yaml
    with:
      env: ${{ inputs.env }}
      apply: ${{ inputs.apply }}
      cwd: deployments/${{ inputs.env }}/1-services
      infra_outputs: ${{ needs.opentofu-infra.outputs.tf_outputs }}
      version: ${{ inputs.version }}
    secrets: inherit
