name: 🪄 Manual OpenTofu Plan & Apply

on:
  workflow_dispatch:
    inputs:
      env:
        description: Target environment (main or dev)
        required: true
        type: choice
        options:
          - main
          - dev
        default: main
      apply:
        description: Set true to run apply after plan
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: write

concurrency:
  group: manual-tofu-${{ inputs.env }}
  cancel-in-progress: false

jobs:
  opentofu-infra:
    name: 🪄 OpenTofu infra (main)
    uses: ./.github/workflows/tf-plan-apply.yaml
    with:
      env: ${{ inputs.env }}
      apply: ${{ inputs.apply }}
      cwd: deployments/main/0-infra
    secrets: inherit

  opentofu-services:
    name: 🪄 OpenTofu services (main)
    needs:
      - opentofu-infra
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    uses: ./.github/workflows/tf-plan-apply.yaml
    with:
      env: ${{ inputs.env }}
      apply: ${{ inputs.apply }}
      cwd: deployments/main/1-services
      infra_outputs: ${{ needs.opentofu-infra.outputs.tf_outputs }}
    secrets: inherit
