name: 📦 Build Frontend and Push to Google Cloud

on:
  workflow_call:
      inputs:
        env:
          required: false
          type: string
          description: "Environment to setup for"
          default: dev
        version:
          required: false
          type: string
          description: "The semantic version to be released"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment override (prod|dev)"
        required: false
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

concurrency:
  group: frontend-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate frontend for ${{ (github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch') && inputs.env || (github.ref_name == 'main' && 'prod' || 'dev') }}
    uses: ./.github/workflows/frontend-validate.yaml
    with:
      env: ${{ inputs.env }}
  build:
    name: Build frontend for ${{ (github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch') && inputs.env || (github.ref_name == 'main' && 'prod' || 'dev') }}
    needs:
      - validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Workflow
        uses: ./.github/actions/setup
        with:
          WIF_PROVIDER: ${{ vars.WIF_PROVIDER }}
          WIF_SA: ${{ vars.WIF_SA }}
          env-file: frontend/.env.development

      - name: 'Get Secrets'
        id: secrets
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            VITE_IMPRESSUM_NAME:${{ vars.PROJECT_ID }}/IMPRESSUM_NAME
            VITE_IMPRESSUM_ADDRESS:${{ vars.PROJECT_ID }}/IMPRESSUM_ADDRESS
            VITE_IMPRESSUM_CITY:${{ vars.PROJECT_ID }}/IMPRESSUM_CITY
            VITE_IMPRESSUM_PHONE:${{ vars.PROJECT_ID }}/IMPRESSUM_PHONE
            VITE_IMPRESSUM_EMAIL:${{ vars.PROJECT_ID }}/IMPRESSUM_EMAIL

      - name: Build Docker Image
        shell: bash
        run: |
          docker build \
            --platform linux/amd64 \
            --tag ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ github.sha }} \
            --build-arg VITE_IMPRESSUM_NAME="${{ steps.secrets.outputs.VITE_IMPRESSUM_NAME }}" \
            --build-arg VITE_IMPRESSUM_ADDRESS="${{ steps.secrets.outputs.VITE_IMPRESSUM_ADDRESS }}" \
            --build-arg VITE_IMPRESSUM_CITY="${{ steps.secrets.outputs.VITE_IMPRESSUM_CITY }}" \
            --build-arg VITE_IMPRESSUM_PHONE="${{ steps.secrets.outputs.VITE_IMPRESSUM_PHONE }}" \
            --build-arg VITE_IMPRESSUM_EMAIL="${{ steps.secrets.outputs.VITE_IMPRESSUM_EMAIL }}" \
            .
        working-directory: frontend
      - name: Push Docker Image to Registry
        shell: bash
        run: |
          gcloud --quiet auth configure-docker "${{ vars.REGION }}-docker.pkg.dev"
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ github.sha }}

      - name: Tag Image as latest
        shell: bash
        run: |
          gcloud artifacts docker tags add \
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ github.sha }} \
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:latest

      - name: Tag with main version
        if: inputs.version
        shell: bash
        run: |
          gcloud artifacts docker tags add \
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ github.sha }} \
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ inputs.version }}
