name: 📦 Build Frontend and Push to Google Cloud

on:
  workflow_call:
      inputs:
        checkout_repo:
          required: false
          type: string
        checkout_ref:
          required: false
          type: string
        env:
          required: false
          type: string
          description: "Environment to setup for"
          default: dev
        version:
          required: false
          type: string
          description: "The semantic version to be released"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment override (prod|dev)"
        required: false
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

concurrency:
  group: frontend-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate frontend for ${{ (github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch') && inputs.env || (github.ref_name == 'main' && 'prod' || 'dev') }}
    uses: ./.github/workflows/frontend-validate.yaml
    with:
      env: ${{ inputs.env }}
      checkout_repo: ${{ inputs.checkout_repo }}
      checkout_ref: ${{ inputs.checkout_ref }}
  build:
    name: Build frontend for ${{ (github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch') && inputs.env || (github.ref_name == 'main' && 'prod' || 'dev') }}
    needs:
      - validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.checkout_repo }}
          ref: ${{ inputs.checkout_ref }}
          fetch-depth: 0

      - name: 📦 Setup Workflow
        uses: ./.github/actions/setup
        with:
          WIF_PROVIDER: ${{ vars.WIF_PROVIDER }}
          WIF_SA: ${{ vars.WIF_SA }}
          env-file: frontend/.env.development

      # Use GitHub environment vars for IMPRESSUM values.
      # These should be configured as environment-level or repository vars
      # with the exact names: VITE_IMPRESSUM_NAME, VITE_IMPRESSUM_ADDRESS,
      # VITE_IMPRESSUM_CITY, VITE_IMPRESSUM_PHONE, VITE_IMPRESSUM_EMAIL.
      # No explicit step is needed to fetch them — they are available via
      # the `vars` context (e.g. ${{ vars.VITE_IMPRESSUM_NAME }}).

      - name: Build Docker Image
        shell: bash
        run: |
          docker build \
          --platform linux/amd64 \
          --tag ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ github.sha }} \
          --build-arg VITE_IMPRESSUM_NAME="${{ vars.VITE_IMPRESSUM_NAME }}" \
          --build-arg VITE_IMPRESSUM_ADDRESS="${{ vars.VITE_IMPRESSUM_ADDRESS }}" \
          --build-arg VITE_IMPRESSUM_CITY="${{ vars.VITE_IMPRESSUM_CITY }}" \
          --build-arg VITE_IMPRESSUM_PHONE="${{ vars.VITE_IMPRESSUM_PHONE }}" \
          --build-arg VITE_IMPRESSUM_EMAIL="${{ vars.VITE_IMPRESSUM_EMAIL }}" \
          --build-arg VITE_SITE_URL="${{ vars.VITE_SITE_URL }}" \
          .
        working-directory: frontend
      - name: Push Docker Image to Registry
        shell: bash
        run: |
          gcloud --quiet auth configure-docker "${{ vars.REGION }}-docker.pkg.dev"
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ github.sha }}

      - name: Tag Image as latest
        shell: bash
        run: |
          gcloud artifacts docker tags add \
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ github.sha }} \
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:latest

      - name: Tag with main version
        if: inputs.version
        shell: bash
        run: |
          gcloud artifacts docker tags add \
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ github.sha }} \
          ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO_NAME }}/swim-gen-frontend:${{ inputs.version }}
