name: 🚀 Build & Deploy (dev)

on:
  push:
    branches: [dev]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  detect-changes:
    name: 🔎 Detect service changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      bff: ${{ steps.filter.outputs.bff }}
      mcp: ${{ steps.filter.outputs.mcp }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - id: filter
        run: |
          changed() { git diff --name-only origin/${{ github.ref_name }}~1 | grep -E "^$1/" >/dev/null && echo true || echo false; }
          echo "backend=$(changed backend)" >> $GITHUB_OUTPUT
          echo "frontend=$(changed frontend)" >> $GITHUB_OUTPUT
          echo "bff=$(changed bff)" >> $GITHUB_OUTPUT
          echo "mcp=$(changed mcp-server)" >> $GITHUB_OUTPUT

  build-backend:
    if: ${{ needs.detect-changes.outputs.backend == 'true' || github.event_name != 'push' }}
    needs: detect-changes
    uses: ./.github/workflows/backend-build.yaml
    with:
      env: dev
    secrets: inherit

  build-frontend:
    if: ${{ needs.detect-changes.outputs.frontend == 'true' || github.event_name != 'push'}}
    needs: detect-changes
    uses: ./.github/workflows/frontend-build.yaml
    with:
      env: dev
    secrets: inherit

  build-bff:
    if: ${{ needs.detect-changes.outputs.bff == 'true' || github.event_name != 'push'}}
    needs: detect-changes
    uses: ./.github/workflows/bff-build.yaml
    with:
      env: dev
    secrets: inherit

  build-mcp:
    if: ${{ needs.detect-changes.outputs.mcp == 'true' || github.event_name != 'push'}}
    needs: detect-changes
    uses: ./.github/workflows/mcp-build.yaml
    with:
      env: dev
    secrets: inherit

  opentofu-infra:
    name: 🪄 OpenTofu infra (dev)
    needs:
        - build-backend
        - build-frontend
        - build-bff
        - build-mcp
    if: always() && !cancelled() && (needs.build-backend.result != 'failure') && (needs.build-frontend.result != 'failure') && (needs.build-bff.result != 'failure') && (needs.build-mcp.result != 'failure')
    uses: ./.github/workflows/tf-plan-apply.yaml
    with:
      env: dev
      apply: true
      cwd: deployments/dev/0-infra
    secrets: inherit

  opentofu-services:
    name: 🪄 OpenTofu services (dev)
    needs:
      - opentofu-infra
    uses: ./.github/workflows/tf-plan-apply.yaml
    with:
      env: dev
      apply: true
      cwd: deployments/dev/1-services
    secrets: inherit

